### ISSUE TITLE
Non-square cores

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#18]
Does the core have to be square? It certainly doesn't visually. Can we have some fun with random core shape generation?

**Comment by gareththegeek** [comment]
The core isn't really a square it is a 1D array, but it's really more of a circle since the addresses wrap round and are relative anyway.  I have toyed with the idea before of presenting the core as a circle which rotates as the executed instruction moves around!  Not very practical but might be fun..

**Comment by dougajmcdonald** [comment]
This is now handled via the logic in the canvas to draw the layout. Would require more work that my initial DOM based version so maybe one for another day

**Comment by dougajmcdonald** [comment]
Closing this as I don't think it adds anything
